import { chromium, expect } from "@playwright/test";
import fs from "node:fs";
import path from "node:path";
function parseEnvFile(content) { const values = {}; for (const rawLine of content.split(/\r?\n/)) { const line = rawLine.trim(); if (!line || line.startsWith("#")) continue; const i = line.indexOf("="); if (i === -1) continue; const key = line.slice(0, i).trim(); let value = line.slice(i + 1).trim(); if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) value = value.slice(1, -1); values[key] = value; } return values; }
const envPath = path.resolve(process.cwd(), ".env"); const localEnv = fs.existsSync(envPath) ? parseEnvFile(fs.readFileSync(envPath, "utf8")) : {}; const readEnv = (name, fallback = "") => process.env[name] ?? localEnv[name] ?? fallback;
const baseURL = readEnv("SMOKE_BASE_URL", "http://127.0.0.1:3000") || "http://127.0.0.1:3000"; const email = readEnv("SMOKE_ARTIST_EMAIL", "smoke-artist@naad-backstage.local"); const password = readEnv("SMOKE_ARTIST_PASSWORD", "SmokeArtist123!");
const shotDir = path.resolve(process.cwd(), ".codex-screenshots/uploader-polish"); fs.mkdirSync(shotDir, { recursive: true });
const browser = await chromium.launch({ headless: true }); const context = await browser.newContext({ baseURL, viewport: { width: 1440, height: 900 } }); const page = await context.newPage(); page.setDefaultTimeout(60_000);
await page.goto("/login", { waitUntil: "domcontentloaded", timeout: 90_000 }); await page.getByRole("textbox", { name: "Email" }).fill(email); await page.getByRole("textbox", { name: "Password" }).fill(password); await page.getByRole("button", { name: /^(?:Sign in|Sign in with password)$/ }).click(); await page.waitForURL(/\\/dashboard/, { waitUntil: "commit", timeout: 90_000 }); await page.goto("/dashboard/uploaded", { waitUntil: "domcontentloaded", timeout: 90_000 }); await expect(page.getByRole("heading", { name: "Uploader", level: 1 })).toBeVisible();
const before = await page.evaluate(() => ({ text: document.body.innerText.slice(0, 1800), active: document.querySelector('.uploader-step-tab.active .step-tab-label')?.textContent?.trim(), titleValue: document.querySelector('#upload-title')?.value }));
await page.getByRole("button", { name: "Continue", exact: true }).click(); await page.waitForTimeout(1500);
const after = await page.evaluate(() => ({ text: document.body.innerText.slice(0, 2500), active: document.querySelector('.uploader-step-tab.active .step-tab-label')?.textContent?.trim(), titleValue: document.querySelector('#upload-title')?.value, dialogs: [...document.querySelectorAll('[role="dialog"], [role="alertdialog"]')].map((el) => el.textContent?.trim().slice(0, 300)), alerts: [...document.querySelectorAll('[role="alert"]')].map((el) => el.textContent?.trim().slice(0, 300)) }));
await page.screenshot({ path: path.join(shotDir, "continue-debug.png"), fullPage: true });
console.log(JSON.stringify({ before, after, url: page.url(), screenshot: path.join(shotDir, "continue-debug.png") }, null, 2)); await browser.close();
