alter table public.artists
  drop constraint if exists artists_avatar_preset_check;

alter table public.artists
  add constraint artists_avatar_preset_check
  check (
    avatar_preset = any (array[
      'aurora',
      'champagne',
      'opal',
      'lagoon',
      'ember',
      'violet',
      'rose',
      'mint',
      'solar',
      'frost',
      'peacock',
      'coral',
      'graphite',
      'citrus',
      'lilac',
      'cobalt',
      'sand',
      'blush',
      'jade',
      'midnight',
      'prism',
      'velvet',
      'orbit',
      'flame',
      'glacier',
      'copper',
      'pearl',
      'marine',
      'moss',
      'ruby',
      'topaz',
      'amethyst',
      'onyx',
      'saffron',
      'cerulean',
      'orchid',
      'seafoam',
      'sunset',
      'nebula',
      'mercury',
      'emerald',
      'ink',
      'dune',
      'bloom',
      'arctic',
      'bronze',
      'sapphire',
      'papaya',
      'pistachio',
      'quartz',
      'lava',
      'skyline',
      'meadow',
      'twilight',
      'honey',
      'smoke',
      'ocean',
      'magma',
      'alpine',
      'noir',
      'custom'
    ])
  );
